services:
  postgres:
    image: postgres:16.0-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ecmp-admin
      POSTGRES_PASSWORD: E8GSiy513zyMy9d?F1jf
      POSTGRES_ROOT_PASSWORD: E8GSiy513zyMy9d?F1jf
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres -U ecmp-admin" ]
      interval: 5s
      retries: 3
    networks:
      - ecmp-network
  backend:
    container_name: ecmp-api
    build:
      context: ecmp-dev/.
      dockerfile: Dockerfile
    image: ecmp-dev:latest
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ecmp-network
  frontend:
    container_name: ecmp-frontend
    build:
      context: ecmp-frontend/.
      dockerfile: Dockerfile
    image: ecmp-frontend:latest
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - ecmp-network
networks:
  ecmp-network: